---
title: "Developing Data Products week 2 project"
author: "Tomasz Dworowy"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, include = TRUE)
```

```{r, load libraries}
if (!require("leaflet"))
  install.packages("leaflet")
library(leaflet)
if (!require("dplyr"))
  install.packages("dplyr")
library(dplyr)
```

```{r, load_data}
#https://data.world/timothyrenner/ufo-sightings/workspace/file?filename=nuforc_reports.csv
data <- read.csv("nuforc_reports.csv")

data_subset <- data %>% select (city_latitude ,city_longitude,posted,summary)

names(data_subset)[names(data_subset) == 'city_latitude'] <- 'lat'
names(data_subset)[names(data_subset) == 'city_longitude'] <- 'long'
data_subset$popup <- paste(data_subset$posted,data_subset$summary)

data_subset <- data_subset %>% select (lat,long,popup)
data_subset <- data_subset[complete.cases(data_subset),]

```

### UFO sitings from The National UFO Reporting Center (nuforc) Online Database


```{r, map}
map1 <-data_subset %>%
      leaflet() %>%
      addTiles() %>%
      addCircleMarkers(lat = ~lat, lng = ~long, popup = ~popup, clusterOptions = markerClusterOptions())

map1
```

